##################
# Run Parameters #
##################

min_chrom_length: 2500000
Polca: True
min_length: 1500
min_quality: 9
Staph: True



BigJobMem: 32000     
BigJobCpu: 16       
SmallJobMem: 4000
